To detect linearly independent rows in a matrix we simply need to place a matrix in Row echelon form, we don't even need to set the diagonal to 1

In [61]:
import numpy as np
import copy

np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

mat1 = np.array([[ 2.0, 3.0,  2.0,  5.0],
                 [ 3.0, 1.0, -3.0,  0.0],
                 [-8.0, 1.0,  3.0,  7.0],
                 [ 0.0, 1.0,  0.0, -9.0]])

mat2 = np.array([[ 2.0,  3.0,  2.0,   5.0],
                 [ 0.0,  2.0,  0.0, -18.0],
                 [-8.0,  1.0,  3.0,   7.0],
                 [ 0.0,  1.0,  0.0,  -9.0]])

mat3 = np.array([[0.0, 2.0,  0.0   , 8.0],
                 [1.0, 3.0,  2.0   , 1.0],
                 [0.0, 2.0,  0.0   , 3.0],
                 [9.0, 5.0, 17.9999, 7.0]])

mat4 = np.array([[ 0.0, 1.0, 0.0,  -9.0],
                 [ 2.0, 3.0, 2.0,   5.0],
                 [ 0.0, 2.0, 0.0, -18.0],
                 [-8.0, 1.0, 3.0,   7.0],
                 [-2.0, 1.0, 0.0,  10.0]])

mat5 = np.array([[ 2.0, 3.0, 2.0,   5.0, 0.0],
                 [ 0.0, 2.0, 0.0, -18.0, 7.0],
                 [-8.0, 1.0, 3.0,   7.0, 2.0],
                 [ 0.0, 1.0, 0.0,  -9.0, 4.0]])
print("Mat1")
print(mat1)
print("Mat2")
print(mat2)
print("Mat3")
print(mat3)
print("Mat4")
print(mat4)
print("Mat5")
print(mat5)


Mat1
[[ 2.  3.  2.  5.]
 [ 3.  1. -3.  0.]
 [-8.  1.  3.  7.]
 [ 0.  1.  0. -9.]]
Mat2
[[  2.   3.   2.   5.]
 [  0.   2.   0. -18.]
 [ -8.   1.   3.   7.]
 [  0.   1.   0.  -9.]]
Mat3
[[ 0.  2.  0.  8.]
 [ 1.  3.  2.  1.]
 [ 0.  2.  0.  3.]
 [ 9.  5. 18.  7.]]
Mat4
[[  0.   1.   0.  -9.]
 [  2.   3.   2.   5.]
 [  0.   2.   0. -18.]
 [ -8.   1.   3.   7.]
 [ -2.   1.   0.  10.]]
Mat5
[[  2.   3.   2.   5.   0.]
 [  0.   2.   0. -18.   7.]
 [ -8.   1.   3.   7.   2.]
 [  0.   1.   0.  -9.   4.]]


In [66]:
def rowEchelon(tmp):
    mat = copy.deepcopy(tmp)
    rows, cols = mat.shape
    
    ind_rows = np.arange(rows)
    threshold = 1E-4
    for i in range(0,rows):

        # Before scaling check to see if the current column is 0, if it is swap with the
        # next row that has a non zero entry              
        
        no_swap = False
        if i < cols:
            if abs(mat[i,i]) < threshold:
                no_swap = True
                for j in range(i+1, rows):
                    if i < cols:
                        if abs(mat[j,i]) > threshold:
                            # swap rows
                            print("Swapping rows %d and %d" % (i,j))
                            for k in range(i,cols):
                                tmp = mat[i,k]
                                mat[i,k] = mat[j,k]
                                mat[j,k] = tmp
                                # Update index
                            tmp_ind = ind_rows[i]
                            ind_rows[i] = ind_rows[j]
                            ind_rows[j] = tmp_ind
                            no_swap = False
                            break
        
        col_to_scale = i
        # If no swap it means that the whole column is 0 so we need to move to the next column
        
        if no_swap:
            for c in range(i+1,cols):
                col_to_scale = c
                if abs(mat[i,c]) < threshold:
                    for j in range(i+1, rows):
                        if i < cols:
                            if mat[j,c] != 0:
                                # swap rows
                                for k in range(i,cols):
                                    tmp = mat[i,k]
                                    mat[i,k] = mat[j,k]
                                    mat[j,k] = tmp
                                    # Update index
                                tmp_ind = ind_rows[i]
                                ind_rows[i] = ind_rows[j]
                                ind_rows[j] = tmp_ind
                                no_swap = False
                                break
                    if no_swap == False:
                        break
        
        
        for j in range(i+1,rows):
            print("row %d value %e" % (i,mat[i,i]))
            if mat[i,col_to_scale] == 0:
                scale = 0.0
            else:
                scale = mat[j,col_to_scale]/mat[i,col_to_scale]
                
            for k in range(i,cols):
                mat[j,k] = mat[j,k]-scale*mat[i,k]

    
    return mat
                

In [67]:
print(rowEchelon(mat1))

row 0 value 2.000000e+00
row 0 value 2.000000e+00
row 0 value 2.000000e+00
row 1 value -3.500000e+00
row 1 value -3.500000e+00
row 2 value -1.128571e+01
[[  2.      3.      2.      5.   ]
 [  0.     -3.5    -6.     -7.5  ]
 [  0.      0.    -11.286  -0.857]
 [  0.      0.      0.    -11.013]]


In [68]:
print(rowEchelon(mat2))

row 0 value 2.000000e+00
row 0 value 2.000000e+00
row 0 value 2.000000e+00
row 1 value 2.000000e+00
row 1 value 2.000000e+00
row 2 value 1.100000e+01
[[  2.   3.   2.   5.]
 [  0.   2.   0. -18.]
 [  0.   0.  11. 144.]
 [  0.   0.   0.   0.]]


In [69]:
print(rowEchelon(mat3))

Swapping rows 0 and 1
row 0 value 1.000000e+00
row 0 value 1.000000e+00
row 0 value 1.000000e+00
row 1 value 2.000000e+00
row 1 value 2.000000e+00
row 2 value 0.000000e+00
[[ 1.  3.  2.  1.]
 [ 0.  2.  0.  8.]
 [ 0.  0.  0. -5.]
 [ 0.  0. -0.  0.]]


In [70]:
print(rowEchelon(mat4))

Swapping rows 0 and 1
row 0 value 2.000000e+00
row 0 value 2.000000e+00
row 0 value 2.000000e+00
row 0 value 2.000000e+00
row 1 value 1.000000e+00
row 1 value 1.000000e+00
row 1 value 1.000000e+00
Swapping rows 2 and 3
row 2 value 1.100000e+01
row 2 value 1.100000e+01
Swapping rows 3 and 4
row 3 value 2.481818e+01
[[  2.      3.      2.      5.   ]
 [  0.      1.      0.     -9.   ]
 [  0.      0.     11.    144.   ]
 [  0.      0.      0.     24.818]
 [  0.      0.      0.      0.   ]]


In [71]:
print(rowEchelon(mat5))

row 0 value 2.000000e+00
row 0 value 2.000000e+00
row 0 value 2.000000e+00
row 1 value 2.000000e+00
row 1 value 2.000000e+00
row 2 value 1.100000e+01
[[  2.    3.    2.    5.    0. ]
 [  0.    2.    0.  -18.    7. ]
 [  0.    0.   11.  144.  -43.5]
 [  0.    0.    0.    0.    0.5]]
